namespace Brokers.Freedom.Models;

public class GetQuoteResponse
{
    public long acd { get; set; }
    public long baf { get; set; }
    public double bap { get; set; }
    public long bas { get; set; }
    public string base_contract_code { get; set; }
    public string base_currency { get; set; }
    public string base_ltr { get; set; }
    public DateTime bat { get; set; }
    public long bbf { get; set; }
    public double bbp { get; set; }
    public long bbs { get; set; }
    public DateTime bbt { get; set; }
    public string c { get; set; }
    public double chg { get; set; }
    public double chg110 { get; set; }
    public double chg22 { get; set; }
    public double chg220 { get; set; }
    public double chg5 { get; set; }
    public double ClosePrice { get; set; }
    public string codesub_nm { get; set; }
    public long cpn { get; set; }
    public long cpp { get; set; }
    public long dpb { get; set; }
    public long dps { get; set; }
    public string emitent_type { get; set; }
    public long fv { get; set; }
    public long init { get; set; }
    public string ipo { get; set; }
    public string issue_nb { get; set; }
    public long kind { get; set; }
    public double ltp { get; set; }
    public string ltr { get; set; }
    public long lts { get; set; }
    public DateTime ltt { get; set; }
    public string marketStatus { get; set; }
    public double maxtp { get; set; }
    public double min_step { get; set; }
    public double mlongp { get; set; }
    public string mrg { get; set; }
    public string mtd { get; set; }
    public long n { get; set; }
    public string name { get; set; }
    public string name2 { get; set; }
    public string ncd { get; set; }
    public long ncp { get; set; }
    public double op { get; set; }
    public string option_type { get; set; }
    public string otc_instr { get; set; }
    public double p110 { get; set; }
    public double p22 { get; set; }
    public double p220 { get; set; }
    public double p5 { get; set; }
    public double pcp { get; set; }
    public double pp { get; set; }
    public string quote_basis { get; set; }
    public long rev { get; set; }
    public string scheme_calc { get; set; }
    public double step_price { get; set; }
    public long strike_price { get; set; }
    public long trades { get; set; }
    public long TradingReferencePrice { get; set; }
    public string TradingSessionSubID { get; set; }
    public long type { get; set; }
    public long UTCOffset { get; set; }
    public string virt_base_instr { get; set; }
    public double vlt { get; set; }
    public long vol { get; set; }
    public string x_agg_futures { get; set; }
    public string x_curr { get; set; }
    public double x_currVal { get; set; }
    public string x_descr { get; set; }
    public long x_dsc1 { get; set; }
    public string x_dsc1_reception { get; set; }
    public long x_dsc2 { get; set; }
    public string x_dsc2_reception { get; set; }
    public long x_dsc3 { get; set; }
    public long x_istrade { get; set; }
    public long x_lot { get; set; }
    public double x_max { get; set; }
    //public long? x_min { get; set; }
   // public long? x_min_lot_q { get; set; }
    public long x_short { get; set; }
    public string x_short_reception { get; set; }
    public long yld { get; set; }
    public long yld_ytm_ask { get; set; }
    public long yld_ytm_bid { get; set; }
    public string code_nm { get; set; }
}